# Generated by Django 5.2.7 on 2025-10-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='titulo_especialidad',
            field=models.CharField(blank=True, help_text="Título o especialidad del instructor (ej: 'Profesor de Historia', 'Ingeniero en Sistemas')", max_length=100, null=True),
        ),
    ]
