# Generated by Django 5.2.7 on 2025-10-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_plantilla_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='Archivo PDF opcional para el curso', null=True, upload_to='cursos/pdfs/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='link_material',
            field=models.URLField(blank=True, help_text='Link opcional para material adicional del curso', null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='titulo_especialidad',
            field=models.CharField(blank=True, help_text="Título o especialidad del instructor (ej: 'Profesor de Historia', 'Ingeniero en Sistemas')", max_length=100, null=True),
        ),
    ]
